// Life is Strange - Ultrawide Fix (Windows front-end)
//
// Copyright (C) 2026 Kiri11.  Free software under the GNU General Public
// License, version 3 or later - see LICENSE for the full terms.
//
// Additional term under GPL-3 section 7(b): every copy or modified version,
// in source or binary form, must preserve this notice and credit the
// original author, Kiri11, with a link to the original project at
// https://github.com/kiri11/Life-is-Strange-Ultrawide-Fix.
//
// This is deliberately a THIN front-end. It contains no patch logic of its own:
// every button runs lis-ultrawide-fix.exe from the cli folder next to this
// program, which is the single source of truth for what gets installed next
// to the executable, written next to the game data and to Engine.ini. Even
// the game search is the installer's ("find"), and so is the list of games
// the fix knows: the window carries no game name, no executable name and no
// path of its own, so it can never disagree with what Install would do, and
// a game added to the installer appears here without a change. An earlier
// version of this file reimplemented the byte patches in C# and silently
// drifted out of sync, which is exactly the bug this structure prevents.
//
// The contract with the installer, which a change to either side must keep
// (crates/installer/src/main.rs states the same):
//   - arguments: install|restore|status|find, --exe PATH, --width W,
//     --height H, --yes, --no-camera, --no-ui, --no-chromatic-fix, --sharpen
//   - "find" prints one "known: <title>\t<short title>\t<exe name>" line per
//     game the fix knows, "Game executable: <path>" for the game it picked,
//     and one "found: <title>\t<short title>\t<path>" line per installed
//     game, the pick first
//   - "status" prints "title:", "status:", "detail:", "files:" and
//     "filesdetail:" lines
//   - exit code 0 is success; 2 is a problem the user can act on
//   - the output is UTF-8, whatever the console code page
//   - the phrase "as administrator" in the output means a permission problem
//     that running again elevated would solve
//
// Build (stock .NET Framework compiler, no SDK required):
//   %WINDIR%\Microsoft.NET\Framework64\v4.0.30319\csc.exe /target:winexe ^
//     /win32icon:LiSUltrawidePatcher.ico ^
//     /out:LiSUltrawidePatcher.exe LiSUltrawidePatcher.cs ^
//     /r:System.dll /r:System.Windows.Forms.dll /r:System.Drawing.dll
//
// That is the same line .github/workflows/build.yml runs, and the exe users get
// is the one it produces - the binary is not in the repository, so it cannot
// drift from this file. The icon is generated by tools/make_icon.py.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Windows.Forms;

// Identity for the file itself - Explorer's Details tab, the digital-signature
// dialog if this is ever signed, and any bug report that quotes a file version.
// Nothing here is shown in the window: the version a user needs to quote is the
// one the installer prints into the log, and these must agree.
//
// The version is the release date plus that day's build number - the same string
// as the release tag (v2026.08.31.1). AssemblyVersion wants bare numbers, so it
// drops the zero padding; AssemblyInformationalVersion carries the exact tag
// text. The CI build rewrites all three from the version it is publishing,
// together with the installer's, so one number identifies the whole fix.
[assembly: AssemblyTitle("Life is Strange - Ultrawide Fix")]
[assembly: AssemblyDescription("Installs the ultrawide and cutscene fix for "
                               + "Life is Strange: Double Exposure and Reunion.")]
[assembly: AssemblyProduct("LiS Ultrawide Fix")]
[assembly: AssemblyCopyright("Copyright (C) 2026 Kiri11. "
                             + "GPL-3.0-or-later; see LICENSE.")]
[assembly: AssemblyVersion("2026.8.31.1")]
[assembly: AssemblyFileVersion("2026.8.31.1")]
[assembly: AssemblyInformationalVersion("2026.08.31.1")]
[assembly: ComVisible(false)]

namespace LiSUltrawidePatcher
{
    public class MainForm : Form
    {
        [DllImport("user32.dll")]
        private static extern bool SetProcessDPIAware();

        private struct Preset
        {
            public string Name;
            public int W, H;
            public Preset(string n, int w, int h) { Name = n; W = w; H = h; }
        }

        private readonly List<Preset> presets = new List<Preset>
        {
            new Preset("5120x2160 (21:9 WUHD 4K)", 5120, 2160),
            new Preset("3440x1440 (21:9 UWQHD)", 3440, 1440),
            new Preset("2560x1080 (21:9 UWD)", 2560, 1080),
            new Preset("3840x1600 (24:10 UW)", 3840, 1600),
            new Preset("5120x1440 (32:9 Super Ultrawide)", 5120, 1440),
            new Preset("3840x1080 (32:9 Super Ultrawide)", 3840, 1080),
            new Preset("7680x2160 (32:9 Super Ultrawide)", 7680, 2160),
            new Preset("3840x1200 (32:10)", 3840, 1200),
            new Preset("2560x1600 (16:10)", 2560, 1600),
            new Preset("1280x800 (16:10 Steam Deck)", 1280, 800),
        };

        /// <summary>A game the installer knows, installed or not (a "known:" line).</summary>
        private struct GameInfo
        {
            public string Title, Short, Exe;
        }

        /// <summary>One executable the list offers: a "found:" line, or a browsed file.</summary>
        private class ExeItem
        {
            public string Title;      // the installer's full title, or null for a file no game claims
            public string Short;      // what the list and the heading call it
            public string Path;
            public string Source;     // where the installer found it, null for a browsed file
            public override string ToString() { return Short + "  -  " + Path; }
        }

        private readonly List<GameInfo> known = new List<GameInfo>();
        private readonly List<ExeItem> found = new List<ExeItem>();   // the installer's pick first

        private TextBox txtExePath, txtWidth, txtHeight, txtLog;
        private ComboBox cmbExe, cmbPresets;
        private CheckBox chkExe, chkGameFiles, chkChromatic, chkSharpen;
        private Button btnBrowse, btnInstall, btnRestore;
        private Label lblExeHeader, lblCustom, lblX, lblExeStatus, lblFilesStatus;
        private TableLayoutPanel exeRow;
        private ToolTip tips;
        private System.Windows.Forms.Timer checkTimer;

        public MainForm()
        {
            InitializeComponent();
            AutoDetect();
        }

        // ------------------------------------------------------------------ UI
        //
        // Everything here auto-sizes. An earlier version positioned each control
        // at a fixed pixel coordinate, which clipped every wrapped description
        // as soon as the system font metrics differed from the ones assumed.

        private const int ContentWidth = 560;
        private const string TitleSuffix = " - Ultrawide Fix";

        private Label Header(string text)
        {
            Label l = new Label();
            l.Text = text;
            l.AutoSize = true;
            l.Margin = new Padding(0, 10, 0, 4);
            l.Font = new Font(Font, FontStyle.Bold);
            return l;
        }

        private CheckBox Option(TableLayoutPanel host, string title, string detail)
        {
            return Option(host, title, detail, true);
        }

        private CheckBox Option(TableLayoutPanel host, string title, string detail,
                                bool on)
        {
            CheckBox c = new CheckBox();
            c.Text = title;
            c.Checked = on;
            c.AutoSize = true;
            c.Margin = new Padding(0, 6, 0, 0);
            c.Font = new Font(Font, FontStyle.Bold);

            Label d = new Label();
            d.Text = detail;
            d.AutoSize = true;
            d.MaximumSize = new Size(ContentWidth - 24, 0);   // wraps, grows down
            d.Margin = new Padding(18, 0, 0, 2);
            d.ForeColor = SystemColors.GrayText;

            host.Controls.Add(c);
            host.Controls.Add(d);
            return c;
        }

        private void InitializeComponent()
        {
            Text = "Life is Strange" + TitleSuffix;     // the game's own title once one is selected
            AutoScaleMode = AutoScaleMode.Font;
            StartPosition = FormStartPosition.CenterScreen;
            Font = new Font("Segoe UI", 9F);
            ClientSize = new Size(600, 760);        // the log gets what the controls leave
            MinimumSize = new Size(560, 640);
            try { Icon = Icon.ExtractAssociatedIcon(Application.ExecutablePath); }
            catch { }

            TableLayoutPanel root = new TableLayoutPanel();
            root.Dock = DockStyle.Fill;
            root.ColumnCount = 1;
            root.Padding = new Padding(16, 8, 16, 12);
            root.AutoSize = false;
            Controls.Add(root);

            // --- game executable
            //
            // One game installed: a path box, as before. Several: a list of
            // them in the same place, since the choice is then between games
            // rather than about a path (see UsePicker). Browse works in both.
            lblExeHeader = Header("Game executable");
            lblExeHeader.MaximumSize = new Size(ContentWidth, 0);   // the long form wraps
            root.Controls.Add(lblExeHeader);

            exeRow = new TableLayoutPanel();
            exeRow.ColumnCount = 2;
            exeRow.Dock = DockStyle.Fill;      // the path box gets the whole row
            exeRow.AutoSize = true;
            exeRow.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            exeRow.Margin = new Padding(0, 0, 0, 4);
            exeRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            exeRow.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            txtExePath = new TextBox();
            txtExePath.Dock = DockStyle.Fill;
            cmbExe = new ComboBox();                     // takes the box's cell in UsePicker
            cmbExe.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbExe.Dock = DockStyle.Fill;
            cmbExe.SelectedIndexChanged += OnExePicked;
            btnBrowse = new Button();
            btnBrowse.Text = "Browse...";
            btnBrowse.AutoSize = true;
            btnBrowse.Margin = new Padding(6, 0, 0, 0);
            btnBrowse.Click += OnBrowse;
            exeRow.Controls.Add(txtExePath, 0, 0);
            exeRow.Controls.Add(btnBrowse, 1, 0);
            root.Controls.Add(exeRow);

            tips = new ToolTip();
            tips.AutoPopDelay = 20000;
            txtExePath.TextChanged += OnExePathChanged;

            checkTimer = new System.Windows.Forms.Timer();          // coalesces typing into one check
            checkTimer.Interval = 400;
            checkTimer.Tick += OnCheckTick;

            lblExeStatus = new Label();
            lblExeStatus.AutoSize = true;
            lblExeStatus.MaximumSize = new Size(ContentWidth, 0);
            lblExeStatus.ForeColor = SystemColors.GrayText;
            lblExeStatus.Margin = new Padding(2, 2, 0, 0);
            root.Controls.Add(lblExeStatus);

            // The second line is about the game's data rather than the exe: it
            // is the only way a user learns that a game update has left the
            // installed UI container behind, since nothing of ours runs at
            // launch to tell them.
            lblFilesStatus = new Label();
            lblFilesStatus.AutoSize = true;
            lblFilesStatus.MaximumSize = new Size(ContentWidth, 0);
            lblFilesStatus.ForeColor = SystemColors.GrayText;
            lblFilesStatus.Margin = new Padding(2, 0, 0, 0);
            root.Controls.Add(lblFilesStatus);

            // --- resolution
            root.Controls.Add(Header("Display resolution"));

            FlowLayoutPanel resRow = new FlowLayoutPanel();
            resRow.AutoSize = true;
            resRow.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            resRow.WrapContents = true;
            resRow.Margin = new Padding(0, 0, 0, 4);

            cmbPresets = new ComboBox();
            cmbPresets.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbPresets.Width = 250;
            cmbPresets.Margin = new Padding(0, 0, 10, 0);
            foreach (Preset p in presets) cmbPresets.Items.Add(p.Name);
            cmbPresets.Items.Add("Custom...");
            cmbPresets.SelectedIndexChanged += OnPresetChanged;
            resRow.Controls.Add(cmbPresets);

            lblCustom = new Label();
            lblCustom.Text = "Custom:";
            lblCustom.AutoSize = true;
            lblCustom.Margin = new Padding(0, 6, 4, 0);
            resRow.Controls.Add(lblCustom);

            txtWidth = new TextBox();
            txtWidth.Width = 52;
            resRow.Controls.Add(txtWidth);

            lblX = new Label();
            lblX.Text = "x";
            lblX.AutoSize = true;
            lblX.Margin = new Padding(2, 6, 2, 0);
            resRow.Controls.Add(lblX);

            txtHeight = new TextBox();
            txtHeight.Width = 52;
            resRow.Controls.Add(txtHeight);
            root.Controls.Add(resRow);

            // --- options
            root.Controls.Add(Header("What to install"));

            TableLayoutPanel opts = new TableLayoutPanel();
            opts.ColumnCount = 1;
            opts.AutoSize = true;
            opts.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            opts.Margin = new Padding(0, 0, 0, 2);

            chkExe = Option(opts, "Ultrawide camera",
                "Hor+ cutscenes, dialogue and exploration - no black bars, and no "
                + "zoom when a dialogue ends. Installs a small library the game "
                + "loads at start; the executable itself is not changed.");
            chkGameFiles = Option(opts, "Full-width UI",
                "Loading screens cover the whole screen and the HUD sits on the "
                + "real screen edge. Adds a mod container next to the game data.");
            chkChromatic = Option(opts, "Disable chromatic aberration",
                "Removes the colour fringing at the widened edges.");
            chkSharpen = Option(opts, "Reduce blurriness",
                "Recommended TSR settings for this resolution.", false);
            root.Controls.Add(opts);

            Label note = new Label();
            note.Text = "The last two write into Engine.ini. Restore removes them.";
            note.AutoSize = true;
            note.MaximumSize = new Size(ContentWidth, 0);
            note.ForeColor = SystemColors.GrayText;
            note.Margin = new Padding(0, 4, 0, 8);
            root.Controls.Add(note);

            // --- actions
            TableLayoutPanel buttons = new TableLayoutPanel();
            buttons.ColumnCount = 2;
            buttons.Dock = DockStyle.Fill;
            buttons.AutoSize = true;
            buttons.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            buttons.Margin = new Padding(0, 0, 0, 8);
            buttons.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            buttons.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));

            btnInstall = new Button();
            btnInstall.Text = "Install";
            btnInstall.Dock = DockStyle.Fill;
            btnInstall.Height = 34;
            btnInstall.Font = new Font(Font.FontFamily, 10F, FontStyle.Bold);
            btnInstall.Margin = new Padding(0, 0, 4, 0);
            btnInstall.Click += OnInstall;

            btnRestore = new Button();
            btnRestore.Text = "Restore original";
            btnRestore.Dock = DockStyle.Fill;
            btnRestore.Height = 34;
            btnRestore.Margin = new Padding(4, 0, 0, 0);
            btnRestore.Click += OnRestore;

            buttons.Controls.Add(btnInstall, 0, 0);
            buttons.Controls.Add(btnRestore, 1, 0);
            root.Controls.Add(buttons);

            // --- log, absorbs whatever space is left
            txtLog = new TextBox();
            txtLog.Multiline = true;
            txtLog.ScrollBars = ScrollBars.Vertical;
            txtLog.ReadOnly = true;
            txtLog.BackColor = Color.White;
            txtLog.Font = new Font("Consolas", 8.5F);
            txtLog.Dock = DockStyle.Fill;
            txtLog.Margin = new Padding(0);
            root.Controls.Add(txtLog);

            // every row hugs its content except the log, which takes the slack
            for (int i = 0; i < root.Controls.Count; i++)
                root.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            root.RowCount = root.Controls.Count;
            root.RowStyles[root.RowCount - 1] = new RowStyle(SizeType.Percent, 100F);
        }

        // ------------------------------------------------------------- helpers

        private void Log(string s)
        {
            if (txtLog.InvokeRequired)
            {
                txtLog.BeginInvoke((MethodInvoker)delegate { Log(s); });
                return;
            }
            txtLog.AppendText(s + Environment.NewLine);
        }

        private void OnPresetChanged(object sender, EventArgs e)
        {
            bool custom = cmbPresets.SelectedIndex == presets.Count;
            txtWidth.Enabled = txtHeight.Enabled = custom;
            if (!custom && cmbPresets.SelectedIndex >= 0)
            {
                Preset p = presets[cmbPresets.SelectedIndex];
                txtWidth.Text = p.W.ToString();
                txtHeight.Text = p.H.ToString();
            }
        }

        // ---- the executable: a path box, or a list of installed games -------

        private bool picker;          // is the list in place of the path box?

        /// <summary>The selected executable's path, trimmed; empty when none.</summary>
        private string ExePath
        {
            get
            {
                if (!picker) return txtExePath.Text.Trim();
                ExeItem item = cmbExe.SelectedItem as ExeItem;
                return item == null ? "" : item.Path;
            }
        }

        /// <summary>Swap the path box for the list of games. Once; never back.</summary>
        private void UsePicker()
        {
            if (picker) return;
            picker = true;
            exeRow.Controls.Remove(txtExePath);
            exeRow.Controls.Add(cmbExe, 0, 0);
        }

        /// <summary>The list entry for a path: what the installer calls the game, else the file name.</summary>
        private ExeItem Describe(string path)
        {
            ExeItem item = new ExeItem();
            item.Path = path;
            item.Short = Path.GetFileName(path);
            foreach (GameInfo g in known)
                if (string.Equals(g.Exe, item.Short, StringComparison.OrdinalIgnoreCase))
                {
                    item.Title = g.Title;
                    item.Short = g.Short;
                }
            return item;
        }

        /// <summary>Make a path the selection, in whichever control is showing.</summary>
        private void SelectExe(string path)
        {
            if (!picker)
            {
                txtExePath.Text = path;
                return;
            }
            for (int i = 0; i < cmbExe.Items.Count; i++)
                if (string.Equals(((ExeItem)cmbExe.Items[i]).Path, path,
                                  StringComparison.OrdinalIgnoreCase))
                {
                    cmbExe.SelectedIndex = i;
                    return;
                }
            cmbExe.Items.Add(Describe(path));
            FitDropDown();
            cmbExe.SelectedIndex = cmbExe.Items.Count - 1;
        }

        /// <summary>The open list wide enough for its longest entry; the closed one cuts the path's end.</summary>
        private void FitDropDown()
        {
            int widest = cmbExe.Width;
            foreach (object item in cmbExe.Items)
                widest = Math.Max(widest, TextRenderer.MeasureText(item.ToString(), cmbExe.Font).Width + 24);
            cmbExe.DropDownWidth = Math.Min(widest, Screen.FromControl(this).WorkingArea.Width - 40);
        }

        private void OnExePicked(object sender, EventArgs e)
        {
            ExeItem item = cmbExe.SelectedItem as ExeItem;
            tips.SetToolTip(cmbExe, item == null ? "" : item.Path);
            UpdateExeHeader();
            SetGameTitle(item == null ? null : item.Title);
            checkTimer.Stop();
            StartExeCheck();             // a click, not typing: check at once
        }

        /// <summary>"Game executable", and with the list, which games it holds; the entry itself says which is selected.</summary>
        private void UpdateExeHeader()
        {
            if (!picker)
            {
                lblExeHeader.Text = "Game executable";
                return;
            }
            lblExeHeader.Text = "Game executable:  " + JoinAnd(CountedNames()) + " found";
        }

        /// <summary>The games found, in order, a game installed twice as "Double Exposure (2 copies)".</summary>
        private List<string> CountedNames()
        {
            List<string> names = new List<string>();
            List<int> counts = new List<int>();
            foreach (ExeItem f in found)
            {
                int i = names.IndexOf(f.Short);
                if (i < 0) { names.Add(f.Short); counts.Add(1); }
                else counts[i]++;
            }
            for (int i = 0; i < names.Count; i++)
                if (counts[i] > 1) names[i] += " (" + counts[i] + " copies)";
            return names;
        }

        /// <summary>The window title names the selected game; the first game the installer knows when none is.</summary>
        private void SetGameTitle(string title)
        {
            if (title == null) title = known.Count > 0 ? known[0].Title : "Life is Strange";
            Text = title + TitleSuffix;
        }

        /// <summary>"A", "A and B", "A, B and C".</summary>
        private static string JoinAnd(List<string> items)
        {
            if (items.Count == 0) return "";
            if (items.Count == 1) return items[0];
            string[] head = items.GetRange(0, items.Count - 1).ToArray();
            return string.Join(", ", head) + " and " + items[items.Count - 1];
        }

        private void OnBrowse(object sender, EventArgs e)
        {
            OpenFileDialog d = new OpenFileDialog();
            // the filter lists every executable the installer knows
            List<string> exes = new List<string>();
            foreach (GameInfo g in known) exes.Add(g.Exe);
            d.Filter = exes.Count == 0
                ? "All files|*.*"
                : "Game executable (" + string.Join(", ", exes.ToArray()) + ")|"
                  + string.Join(";", exes.ToArray()) + "|All files|*.*";
            d.RestoreDirectory = true;
            // start where the current selection is, with that file selected
            string current = ExePath;
            if (current.Length > 0)
            {
                try
                {
                    string dir = Path.GetDirectoryName(Path.GetFullPath(current));
                    if (Directory.Exists(dir)) d.InitialDirectory = dir;
                    if (File.Exists(current)) d.FileName = Path.GetFileName(current);
                }
                catch { }
            }
            if (d.ShowDialog() == DialogResult.OK) SelectExe(d.FileName);
        }

        // ---- the installer ------------------------------------------------

        private const string CliName = "lis-ultrawide-fix.exe";
        private const string CliWhere = "in the cli folder next to this program";

        /// <summary>The installer: in the cli folder next to this program (the
        /// archive's layout), else next to it (a build tree); null when neither.</summary>
        private static string CliPath()
        {
            string here = AppDomain.CurrentDomain.BaseDirectory;
            foreach (string dir in new string[] { Path.Combine(here, "cli"), here })
            {
                string p = Path.Combine(dir, CliName);
                if (File.Exists(p)) return p;
            }
            return null;
        }

        /// <summary>Start settings shared by every run of the installer.</summary>
        //
        // The encodings matter: the installer writes UTF-8 to a pipe, and this
        // process must read the same, or a game path with a non-ASCII
        // character in it arrives as mojibake. Both streams are always
        // redirected: .NET refuses to start a process that carries an encoding
        // for a stream it is not capturing.
        private static ProcessStartInfo Launch(string cli, string args)
        {
            ProcessStartInfo psi = new ProcessStartInfo(cli, args);
            psi.UseShellExecute = false;
            psi.CreateNoWindow = true;
            psi.RedirectStandardOutput = true;
            psi.RedirectStandardError = true;
            psi.StandardOutputEncoding = new UTF8Encoding(false);
            psi.StandardErrorEncoding = new UTF8Encoding(false);
            psi.WorkingDirectory = Path.GetDirectoryName(cli);
            return psi;
        }

        private static string Quote(string s)
        {
            return "\"" + s + "\"";
        }

        /// <summary>Run the installer to completion, out of sight; its output, or null.</summary>
        private static string RunCli(string args)
        {
            string cli = CliPath();
            if (cli == null) return null;
            try
            {
                using (Process p = Process.Start(Launch(cli, args)))
                {
                    // drained on its own thread: a long complaint on stderr
                    // would otherwise fill its pipe and hang while we read
                    // the other one
                    Process capture = p;
                    ThreadPool.QueueUserWorkItem(delegate
                    {
                        try { capture.StandardError.ReadToEnd(); }
                        catch { }
                    });
                    string text = p.StandardOutput.ReadToEnd();
                    p.WaitForExit();
                    return text;
                }
            }
            catch { return null; }
        }

        /// <summary>The tab-separated fields of a "known:" or "found:" line, or null when there are not n of them.</summary>
        private static string[] Fields(string line, string prefix, int n)
        {
            string[] f = line.Substring(prefix.Length).Split('\t');
            return f.Length == n ? f : null;
        }

        private void AutoDetect()
        {
            // executable: the installer's own search, so the window agrees
            // with what Install would do; the games it knows come along
            if (CliPath() == null)
            {
                Log(CliName + " must be " + CliWhere + ". Unpack the whole archive.");
            }
            else
            {
                List<string> notes = new List<string>();
                string text = RunCli("find") ?? "";
                foreach (string line in text.Split('\n'))
                {
                    string t = line.Trim();
                    string[] f;
                    if (t.StartsWith("known: ") && (f = Fields(t, "known: ", 3)) != null)
                    {
                        GameInfo g = new GameInfo();
                        g.Title = f[0];
                        g.Short = f[1];
                        g.Exe = f[2];
                        known.Add(g);
                    }
                    else if (t.StartsWith("found: ") && (f = Fields(t, "found: ", 4)) != null)
                    {
                        ExeItem item = new ExeItem();
                        item.Title = f[0];
                        item.Short = f[1];
                        item.Path = f[2];
                        item.Source = f[3];
                        found.Add(item);
                    }
                    else if (t.StartsWith("Note: ")) notes.Add(t);
                }
                if (found.Count > 1)
                {
                    // several games, or copies of one: the list, the installer's
                    // pick selected
                    UsePicker();
                    foreach (ExeItem item in found) cmbExe.Items.Add(item);
                    FitDropDown();
                    foreach (ExeItem item in found) Log("Found " + item.Short + " via " + item.Source + ".");
                    Log("Pick one to fix. Each is fixed on its own: install once for each.");
                    foreach (string n in notes) Log(n);
                    cmbExe.SelectedIndex = 0;
                }
                else if (found.Count == 1)
                {
                    txtExePath.Text = found[0].Path;
                    Log("Found " + found[0].Short + " via " + found[0].Source + ".");
                }
                else
                {
                    Log("Could not find the game automatically - use Browse.");
                }
            }
            SetGameTitle(picker ? null : Describe(ExePath).Title);
            UpdateExeHeader();

            // resolution: select the preset matching this display, else Custom
            Rectangle b = Screen.PrimaryScreen.Bounds;
            txtWidth.Text = b.Width.ToString();
            txtHeight.Text = b.Height.ToString();
            int match = -1;
            for (int i = 0; i < presets.Count; i++)
                if (presets[i].W == b.Width && presets[i].H == b.Height) { match = i; break; }
            cmbPresets.SelectedIndex = (match >= 0) ? match : presets.Count;
            Log(string.Format("Detected display: {0}x{1}{2}", b.Width, b.Height,
                              match >= 0 ? "" : "  (using Custom)"));

            // show the start of the path rather than opening mid-selection
            txtExePath.SelectionLength = 0;
            txtExePath.SelectionStart = 0;
            ActiveControl = btnInstall;
        }

        // ---- status badges ------------------------------------------------
        // Whether the fix's loader is next to the executable, what it reported
        // at the last launch, and whether the UI container is current, is
        // decided by "lis-ultrawide-fix status". Keeping the answer there
        // means the badges can never disagree with what Install would do.

        private const string GlyphOk = "✔";      // heavy check mark
        private const string GlyphWarn = "⚠";    // warning sign
        private static readonly Color OkColor = Color.FromArgb(0, 128, 0);
        private static readonly Color WarnColor = Color.FromArgb(190, 100, 0);

        private int checkToken;

        private void SetExeStatus(string glyph, Color color, string text, string tip)
        {
            lblExeStatus.ForeColor = color;
            lblExeStatus.Text = (glyph.Length > 0 ? glyph + "  " : "") + text;
            tips.SetToolTip(lblExeStatus, tip ?? text);
        }

        private void SetFilesStatus(string glyph, Color color, string text, string tip)
        {
            lblFilesStatus.ForeColor = color;
            lblFilesStatus.Text = text.Length == 0
                ? "" : (glyph.Length > 0 ? glyph + "  " : "") + text;
            tips.SetToolTip(lblFilesStatus, tip ?? text);
        }

        private void OnExePathChanged(object sender, EventArgs e)
        {
            tips.SetToolTip(txtExePath, txtExePath.Text.Trim());
            checkTimer.Stop();
            checkTimer.Start();          // coalesce typing into one check
        }

        private void OnCheckTick(object sender, EventArgs e)
        {
            checkTimer.Stop();
            StartExeCheck();
        }

        private void StartExeCheck()
        {
            if (!IsHandleCreated) return;
            string path = ExePath;
            int token = ++checkToken;

            if (path.Length == 0)
            {
                SetExeStatus("", SystemColors.GrayText, "No executable selected.", null);
                SetFilesStatus("", SystemColors.GrayText, "", null);
                SetGameTitle(null);
                return;
            }
            if (!File.Exists(path))
            {
                SetExeStatus(GlyphWarn, WarnColor, "There is no file at that path.", path);
                SetFilesStatus("", SystemColors.GrayText, "", null);
                SetGameTitle(null);
                return;
            }
            SetExeStatus("", SystemColors.GrayText,
                         "Checking " + Path.GetFileName(path) + "...", path);
            SetFilesStatus("", SystemColors.GrayText, "", null);

            ThreadPool.QueueUserWorkItem(delegate
            {
                string title, status, detail, files, filesDetail;
                RunCheck(path, out title, out status, out detail, out files, out filesDetail);
                if (token != checkToken) return;             // superseded
                try
                {
                    BeginInvoke((MethodInvoker)delegate
                    {
                        if (token != checkToken) return;
                        ApplyStatus(status, detail, title);
                        ApplyFilesStatus(files, filesDetail);
                    });
                }
                catch { }                                    // form already gone
            });
        }

        /// <summary>The full-width UI container: is it there, and is it current?</summary>
        private void ApplyFilesStatus(string status, string detail)
        {
            switch (status)
            {
                case "current":
                    SetFilesStatus(GlyphOk, OkColor, "Full-width UI " + detail + ".", detail);
                    break;
                case "stale":
                    SetFilesStatus(GlyphWarn, WarnColor,
                                   "Full-width UI was built for a different build of the "
                                   + "game - Install again before playing.", detail);
                    break;
                case "unrecorded":
                case "incomplete":
                    SetFilesStatus(GlyphWarn, WarnColor,
                                   "Full-width UI needs installing again.", detail);
                    break;
                case "none":
                    SetFilesStatus("", SystemColors.GrayText,
                                   "Full-width UI is not installed.", detail);
                    break;
                default:
                    SetFilesStatus("", SystemColors.GrayText, "", detail);
                    break;
            }
        }

        /// <summary>The installer's one-line detail as a sentence of its own.</summary>
        private static string Sentence(string detail)
        {
            if (string.IsNullOrEmpty(detail)) return null;
            string s = char.ToUpper(detail[0]) + detail.Substring(1);
            return s.EndsWith(".") ? s : s + ".";
        }

        private void ApplyStatus(string status, string detail, string title)
        {
            // the title is the installer's word on which game this is; it
            // means nothing for a file no game claims
            bool isGame = status == "installed" || status == "outdated"
                          || status == "foreign" || status == "none";
            SetGameTitle(isGame ? title : null);
            switch (status)
            {
                case "installed":
                    if (detail != null && detail.Contains("not applied"))
                        SetExeStatus(GlyphWarn, WarnColor,
                                     "Loader installed, but the game did not take the fix at "
                                     + "the last launch - see LiSUltrawideCamera.log.", detail);
                    else
                        SetExeStatus(GlyphOk, OkColor, "Ultrawide camera loader installed.", detail);
                    break;
                case "outdated":
                    SetExeStatus(GlyphWarn, WarnColor,
                                 "A different version of the loader is installed - Install "
                                 + "updates it.", detail);
                    break;
                case "foreign":
                    SetExeStatus(GlyphWarn, WarnColor,
                                 "Another program's winhttp.dll is next to the game - the fix "
                                 + "will not replace it.", detail);
                    break;
                case "none":
                    SetExeStatus("", SystemColors.GrayText,
                                 "Ultrawide camera loader is not installed.", detail);
                    break;
                case "notgame":
                    // the installer names every executable it knows
                    SetExeStatus(GlyphWarn, WarnColor,
                                 Sentence(detail) ?? "That is not the game's executable.", detail);
                    break;
                case "missing":
                    SetExeStatus(GlyphWarn, WarnColor, "There is no file at that path.", detail);
                    break;
                case "nocli":
                    SetExeStatus("", SystemColors.GrayText,
                                 "Not checked - " + CliName + " is not " + CliWhere + ".", null);
                    break;
                default:
                    SetExeStatus("", SystemColors.GrayText, "Could not check this file.", detail);
                    break;
            }
        }

        /// <summary>"lis-ultrawide-fix status", out of sight; never prompts.</summary>
        private void RunCheck(string path, out string title, out string status, out string detail,
                              out string files, out string filesDetail)
        {
            title = null;
            status = "error";
            detail = null;
            files = "error";
            filesDetail = null;
            if (CliPath() == null) { status = "nocli"; return; }
            string text = RunCli("status --exe " + Quote(path));
            if (text == null) return;
            foreach (string line in text.Split('\n'))
            {
                string t = line.Trim();
                if (t.StartsWith("title: ")) title = t.Substring(7).Trim();
                else if (t.StartsWith("status: ")) status = t.Substring(8).Trim();
                else if (t.StartsWith("detail: ")) detail = t.Substring(8).Trim();
                else if (t.StartsWith("files: ")) files = t.Substring(7).Trim();
                else if (t.StartsWith("filesdetail: ")) filesDetail = t.Substring(13).Trim();
            }
        }

        protected override void OnShown(EventArgs e)
        {
            base.OnShown(e);
            StartExeCheck();
        }

        // ---- running Install and Restore ----------------------------------

        private void Run(string args)
        {
            string cli = CliPath();
            if (cli == null)
            {
                MessageBox.Show(CliName + " must be " + CliWhere + ". Unpack the "
                                + "whole archive, not just this file.",
                                "Missing " + CliName, MessageBoxButtons.OK,
                                MessageBoxIcon.Error);
                return;
            }

            btnInstall.Enabled = btnRestore.Enabled = false;
            txtLog.Clear();
            Log("> " + cli + " " + args);
            Log("");

            bool denied = false;          // was it a permissions refusal?
            Process proc = new Process();
            proc.StartInfo = Launch(cli, args);
            proc.EnableRaisingEvents = true;
            DataReceivedEventHandler onLine = delegate(object s, DataReceivedEventArgs e)
            {
                if (e.Data == null) return;
                // the installer ends that advice this way ("run this
                // installer as administrator")
                if (e.Data.IndexOf("as administrator",
                                   StringComparison.OrdinalIgnoreCase) >= 0)
                    denied = true;
                Log(e.Data);
            };
            proc.OutputDataReceived += onLine;
            proc.ErrorDataReceived += onLine;
            proc.Exited += delegate
            {
                int code = proc.ExitCode;
                BeginInvoke((MethodInvoker)delegate
                {
                    Log("");
                    Log(code == 0 ? "Finished." : "Failed (exit code " + code + ").");
                    btnInstall.Enabled = btnRestore.Enabled = true;
                    StartExeCheck();           // what is installed just changed
                    if (code != 0 && denied) OfferElevation(cli, args);
                });
            };
            try
            {
                proc.Start();
                proc.BeginOutputReadLine();
                proc.BeginErrorReadLine();
            }
            catch (Exception ex)
            {
                Log("Could not start " + cli + ": " + ex.Message);
                btnInstall.Enabled = btnRestore.Enabled = true;
            }
        }

        // A game under Program Files - Steam's default - cannot be written by an
        // ordinary process, and "right-click, Run as administrator" is not
        // something this program can assume anyone knows. So it offers, and
        // repeats the exact same command with the elevation prompt attached.
        private void OfferElevation(string cli, string args)
        {
            if (MessageBox.Show(
                    "Windows refused permission to write the game files.\r\n\r\n"
                    + "This happens when the game is installed under Program "
                    + "Files. Run the same install again as administrator?",
                    "Administrator rights needed", MessageBoxButtons.YesNo,
                    MessageBoxIcon.Question) != DialogResult.Yes)
                return;
            RunElevated(cli, args);
        }

        /// <summary>The same command, elevated, with its output in a file.</summary>
        //
        // An elevated child cannot have its pipes redirected (that needs
        // UseShellExecute = false, which in turn cannot request elevation), so
        // it is run through cmd with its output sent to a temporary file, which
        // is poured into the log when it finishes.
        private void RunElevated(string cli, string args)
        {
            string log = Path.Combine(Path.GetTempPath(), "lisde-elevated.log");
            try { if (File.Exists(log)) File.Delete(log); }
            catch { }

            // Elevation can land in a different account - a standard user who
            // types an administrator's password gets that administrator's
            // profile - and then %LOCALAPPDATA% is the wrong one: Engine.ini
            // would be written where the game will never read it. It is the
            // invoking user's, so pass theirs through.
            string local = Environment.GetFolderPath(
                Environment.SpecialFolder.LocalApplicationData);
            string keepLocal = string.IsNullOrEmpty(local)
                ? "" : "set \"LOCALAPPDATA=" + local + "\"&& ";
            string command = keepLocal + Quote(cli) + " " + args
                             + " > " + Quote(log) + " 2>&1";
            ProcessStartInfo psi = new ProcessStartInfo("cmd.exe", "/c \"" + command + "\"");
            psi.UseShellExecute = true;          // required for the elevation verb
            psi.Verb = "runas";
            psi.WindowStyle = ProcessWindowStyle.Hidden;
            psi.WorkingDirectory = Path.GetDirectoryName(cli);

            btnInstall.Enabled = btnRestore.Enabled = false;
            Log("");
            Log("Running as administrator - the output appears when it finishes.");
            Process proc;
            try
            {
                proc = Process.Start(psi);
            }
            catch (Exception ex)
            {
                // 1223 is the user dismissing the UAC prompt: not an error
                Log(ex is System.ComponentModel.Win32Exception
                    && ((System.ComponentModel.Win32Exception)ex).NativeErrorCode == 1223
                    ? "Cancelled - nothing was changed."
                    : "Could not start it as administrator: " + ex.Message);
                btnInstall.Enabled = btnRestore.Enabled = true;
                return;
            }
            proc.EnableRaisingEvents = true;
            proc.Exited += delegate
            {
                int code = proc.ExitCode;
                string text = "";
                try
                {
                    if (File.Exists(log))
                        text = File.ReadAllText(log, new UTF8Encoding(false));
                }
                catch (Exception ex) { text = "(could not read the output: " + ex.Message + ")"; }
                BeginInvoke((MethodInvoker)delegate
                {
                    foreach (string line in text.Replace("\r\n", "\n").Split('\n'))
                        if (line.Length > 0) Log(line);
                    Log("");
                    Log(code == 0 ? "Finished." : "Failed (exit code " + code + ").");
                    btnInstall.Enabled = btnRestore.Enabled = true;
                    StartExeCheck();
                    try { if (File.Exists(log)) File.Delete(log); }
                    catch { }
                });
            };
        }

        /// <summary>The arguments both buttons share, or null when the form is not ready.</summary>
        private string CommonArgs()
        {
            string exe = ExePath;
            if (exe.Length == 0)
            {
                MessageBox.Show("Select the game executable first.", "No executable",
                                MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return null;
            }
            int w, h;
            if (!int.TryParse(txtWidth.Text.Trim(), out w) ||
                !int.TryParse(txtHeight.Text.Trim(), out h) || w <= 0 || h <= 0)
            {
                MessageBox.Show("Enter a valid resolution.", "Invalid resolution",
                                MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return null;
            }
            return "--exe " + Quote(exe) + " --width " + w
                   + " --height " + h + " --yes";
        }

        private void OnInstall(object sender, EventArgs e)
        {
            string common = CommonArgs();
            if (common == null) return;
            if (!chkExe.Checked && !chkGameFiles.Checked &&
                !chkChromatic.Checked && !chkSharpen.Checked)
            {
                MessageBox.Show("Nothing is selected.", "Nothing to do",
                                MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }
            string args = "install " + common;
            if (!chkExe.Checked) args += " --no-camera";
            if (!chkGameFiles.Checked) args += " --no-ui";
            if (!chkChromatic.Checked) args += " --no-chromatic-fix";
            if (chkSharpen.Checked) args += " --sharpen";
            Run(args);
        }

        private void OnRestore(object sender, EventArgs e)
        {
            string common = CommonArgs();
            if (common == null) return;
            Run("restore " + common);
        }

        [STAThread]
        public static void Main()
        {
            // Must happen BEFORE any window exists - doing it later makes Windows
            // re-map an already-created form and shrink it by the DPI factor.
            try { SetProcessDPIAware(); }
            catch { }
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MainForm());
        }
    }
}
